require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe CollagesController do

  # This should return the minimal set of attributes required to create a valid
  # Collage. As you add validations to Collage, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    { "title" => "MyString", "author" => "John Doe","selected_images" => "1-2-3" }
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # CollagesController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all collages as @collages" do
      collage = Collage.create! valid_attributes
      get :index, {}, valid_session
      assigns(:collages).should eq([collage])
    end
  end

  describe "GET show" do
    it "assigns the requested collage as @collage" do
      collage = Collage.create! valid_attributes
      get :show, {:id => collage.to_param}, valid_session
      assigns(:collage).should eq(collage)
    end
  end

  describe "GET new" do
    it "assigns a new collage as @collage" do
      get :new, {}, valid_session
      assigns(:collage).should be_a_new(Collage)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Collage" do
        expect {
          post :create, {:collage => valid_attributes}, valid_session
        }.to change(Collage, :count).by(1)
      end

      it "assigns a newly created collage as @collage" do
        post :create, {:collage => valid_attributes}, valid_session
        assigns(:collage).should be_a(Collage)
        assigns(:collage).should be_persisted
      end

      it "redirects to the created collage" do
        post :create, {:collage => valid_attributes}, valid_session
        response.should redirect_to(collages_path)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved collage as @collage" do
        # Trigger the behavior that occurs when invalid params are submitted
        Collage.any_instance.stub(:save).and_return(false)
        post :create, {:collage => { "title" => "invalid value" }}, valid_session
        assigns(:collage).should be_a_new(Collage)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Collage.any_instance.stub(:save).and_return(false)
        post :create, {:collage => { "title" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end
end
